version: '3.7'

services:
    virtuoso:
      image: aksw/virtuoso-backport:v1.1.0-virtuoso7.2.4-patch
      container_name: pfarrerbuch_virtuoso
      restart: unless-stopped
      env_file:
        - variables.env
      environment:
        SPARQL_UPDATE: "true"
        VIRT_Parameters_DirsAllowed: "., /usr/local/virtuoso-opensource/share/virtuoso/vad, /models"
      volumes:
        - libvirtodbc:/usr/local/virtuoso-opensource/lib
        - models:/models
      healthcheck:
        test: wget --spider --server-response --tries=1 http://localhost:8890/ 2>&1 | grep 'HTTP/' | awk '{print $$2}' | tail -n 1 | xargs -I % test % -eq '200'
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 40s

    phpserver:
      image: aksw/php-5.6-fpm-odbc-virtuoso
      container_name: pfarrerbuch_php
      restart: unless-stopped
      volumes:
        - ontowiki:/var/www/html/
        - libvirtodbc:/usr/local/virtuoso-opensource/lib
        - models:/models
      links:
        - virtuoso

    nginx:
      image: aksw/nginx-ontowiki
      container_name: pfarrerbuch_nginx
      restart: unless-stopped
      volumes:
        - ontowiki:/var/www/html/
      links:
        - phpserver
      ports:
        - "8080:80"

    ontowiki:
      image: aksw/pfarrerbuch-dockerizing
      container_name: pfarrerbuch_ontowiki
      restart: unless-stopped
      env_file:
        - variables.env
      volumes:
        - ontowiki:/var/www/html/
        - models:/models
      links:
        - virtuoso

    importer:
      image: aksw/dld-load-virtuoso
      container_name: pfarrerbuch_importer
      depends_on:
        - "virtuoso"
      env_file:
        - variables.env
      environment:
        VIRTUOSO_DATA_DIR: "/models"
      volumes:
        - models:/models
        - /data/pfarrerbuch/ssh/known_hosts:/root/.ssh/known_hosts
        - ${SSH_AUTH_SOCK}:/var/run/ssh-agent.sock
      command: /virtuoso/git_import.sh

    exporter:
      image: aksw/dld-load-virtuoso
      container_name: pfarrerbuch_exporter
      restart: unless-stopped
      depends_on:
        - "virtuoso"
      env_file:
        - variables.env
      environment:
        VIRTUOSO_DATA_DIR: "/models"
        CRON_JOB: "dump"
        CRON_TIMES: "5,20,35,50 * * * *"
      volumes:
        - models:/models
        - /data/pfarrerbuch/ssh/known_hosts:/root/.ssh/known_hosts
        - ${SSH_AUTH_SOCK}:/var/run/ssh-agent.sock
      command: /virtuoso/envsetter.sh


volumes:
    libvirtodbc: {}
    ontowiki: {}
    models: {}
