version: '2'

services:
    virtuoso:
      image: tenforce/virtuoso:1.1.0-virtuoso7.2.4
      env_file:
        - variables.env
      environment:
        SPARQL_UPDATE: "true"
      volumes:
        - data:/data
        - lib:/usr/local/virtuoso-opensource/lib

    phpserver:
      image: aksw/php-5.6-fpm-odbc-virtuoso
      volumes_from:
        - ontowiki
        - virtuoso
      links:
        - virtuoso

    nginx:
      image: aksw/nginx-ontowiki
      volumes_from:
        - ontowiki
      links:
        - phpserver
      ports:
        - "8080:80"

    ontowiki:
      image: pfarrerbuch-dockerizing:local
      container_name: pfarrerbuch
      env_file:
        - variables.env
      volumes:
        - $SSH_AUTH_SOCK:/var/run/ssh-agent.sock
        - /data/pfarrerbuch/ssh/known_hosts:/root/.ssh/known_hosts
        - /data/pfarrerbuch/models:/models
      links:
        - virtuoso
volumes:
    data: {}
    lib: {}
