version: '3'

services:
    virtuoso:
      image: tenforce/virtuoso:1.1.0-virtuoso7.2.4
      env_file:
        - variables.env
      environment:
        SPARQL_UPDATE: "true"
      volumes:
        - data:/data
        - lib:/usr/local/virtuoso-opensource/lib

    phpserver:
      image: aksw/php-5.6-fpm-odbc-virtuoso
      volumes:
        - data
        - lib
        - ssh
        - knowndriver
        - models
      links:
        - virtuoso

    nginx:
      image: aksw/nginx-ontowiki
      volumes:
        - ssh
        - knowndriver
        - models
      links:
        - phpserver
      ports:
        - "8080:80"

    ontowiki:
      image: pfarrerbuch-dockerizing:local
      container_name: pfarrerbuch
      env_file:
        - variables.env
      environment:
        - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - SSH_AUTH_SOCK=/var/run/ssh-agent.sock
      volumes:
        - $SSH_AUTH_SOCK:/var/run/ssh-agent.sock
        - knowndriver:/root/.ssh/known_hosts
        - models:/models
      links:
        - virtuoso
volumes:
    data: {}
    lib: {}
    knowndriver:
        driver: local
        driver_opts:
            type: none
            device: /data/pfarrerbuch/ssh/known_hosts
            o: bind
    models:
        driver: local
        driver_opts:
            type: none
            device: /data/pfarrerbuch/models
            o: bind
