version: '3.7'

services:
    virtuoso:
      image: aksw/virtuoso-backport:v1.1.0-virtuoso7.2.4-patch
      container_name: pfarrerbuch_virtuoso
      env_file:
        - variables.env
      environment:
        SPARQL_UPDATE: "true"
        VIRT_Parameters_DirsAllowed: "., /usr/local/virtuoso-opensource/share/virtuoso/vad, /models"
      volumes:
        - libvirtodbc:/usr/local/virtuoso-opensource/lib
        - models:/models
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8890/"]
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 40s

    phpserver:
      image: aksw/php-5.6-fpm-odbc-virtuoso
      container_name: pfarrerbuch_php
      volumes:
        - ontowiki:/var/www/html/
        - libvirtodbc:/usr/local/virtuoso-opensource/lib
        - models:/models
      links:
        - virtuoso

    nginx:
      image: aksw/nginx-ontowiki
      container_name: pfarrerbuch_nginx
      volumes:
        - ontowiki:/var/www/html/
      links:
        - phpserver
      ports:
        - "8080:80"

    ontowiki:
      image: aksw/pfarrerbuch-dockerizing
      container_name: pfarrerbuch_ontowiki
      env_file:
        - variables.env
      volumes:
        - ontowiki:/var/www/html/
        - models:/models
        - ${SSH_AUTH_SOCK}:/var/run/ssh-agent.sock
        - /data/pfarrerbuch/ssh/known_hosts:/root/.ssh/known_hosts
      links:
        - virtuoso

    importer:
      image: aksw/dld-load-virtuoso
      container_name: pfarrerbuch_importer
      # entrypoint: "sleep 10m"
      depends_on:
        - "virtuoso"
      env_file:
        - variables.env
      environment:
        VIRTUOSO_IMPORT_DIR: "/models"
      volumes:
        - models:/models

volumes:
    libvirtodbc: {}
    ontowiki: {}
    models:
        driver: local
        driver_opts:
            type: none
            device: /data/pfarrerbuch/models
            o: bind
